from typing import Dict, List

DEFAULT_SYNONYMS = {
    "en": {
        "car": ["automobile", "vehicle", "auto"],
        "automobile": ["car", "vehicle", "auto"],
        "auto": ["car", "automobile", "vehicle"],
        "vehicle": ["car", "automobile", "auto"],
        "computer": ["pc", "laptop", "desktop", "machine"],
        "pc": ["computer", "laptop", "desktop"],
        "laptop": ["computer", "pc", "notebook"],
        "notebook": ["laptop", "computer"],
        "phone": ["mobile", "cellphone", "smartphone", "mobile phone"],
        "mobile": ["phone", "cellphone", "smartphone"],
        "cellphone": ["phone", "mobile", "smartphone"],
        "smartphone": ["phone", "mobile", "cellphone"],
        "movie": ["film", "motion picture", "flick"],
        "film": ["movie", "motion picture", "flick"],
        "picture": ["image", "photo", "photograph"],
        "image": ["picture", "photo", "photograph"],
        "photo": ["picture", "image", "photograph"],
        "photograph": ["picture", "image", "photo"],
        "house": ["home", "building", "residence"],
        "home": ["house", "residence", "dwelling"],
        "building": ["house", "structure", "construction"],
        "work": ["job", "employment", "occupation", "career"],
        "job": ["work", "employment", "occupation"],
        "employment": ["work", "job", "occupation"],
        "occupation": ["work", "job", "employment", "career"],
        "career": ["work", "job", "occupation", "profession"],
        "big": ["large", "huge", "giant", "enormous", "massive"],
        "large": ["big", "huge", "giant", "enormous", "massive"],
        "small": ["tiny", "little", "miniature", "compact"],
        "tiny": ["small", "little", "miniature"],
        "little": ["small", "tiny", "miniature"],
        "fast": ["quick", "rapid", "speedy", "swift"],
        "quick": ["fast", "rapid", "speedy", "swift"],
        "rapid": ["fast", "quick", "speedy", "swift"],
        "slow": ["sluggish", "leisurely", "gradual"],
        "good": ["great", "excellent", "wonderful", "superb", "fine"],
        "great": ["good", "excellent", "wonderful", "superb"],
        "excellent": ["good", "great", "wonderful", "superb"],
        "bad": ["poor", "terrible", "awful", "horrible"],
        "poor": ["bad", "terrible", "awful"],
        "happy": ["glad", "pleased", "delighted", "joyful"],
        "glad": ["happy", "pleased", "delighted"],
        "sad": ["unhappy", "sorrowful", "miserable", "depressed"],
        "unhappy": ["sad", "sorrowful", "miserable"],
        "beautiful": ["pretty", "attractive", "gorgeous", "lovely"],
        "pretty": ["beautiful", "attractive", "gorgeous", "lovely"],
        "ugly": ["unattractive", "hideous", "unsightly"],
        "unattractive": ["ugly", "hideous", "unsightly"],
        "easy": ["simple", "straightforward", "effortless"],
        "simple": ["easy", "straightforward", "effortless"],
        "difficult": ["hard", "challenging", "tough", "complicated"],
        "hard": ["difficult", "challenging", "tough", "complicated"],
        "new": ["recent", "fresh", "modern", "latest"],
        "recent": ["new", "fresh", "latest"],
        "old": ["ancient", "vintage", "aged", "elderly"],
        "ancient": ["old", "vintage", "aged"],
        "hot": ["warm", "heated", "scorching"],
        "warm": ["hot", "heated", "cozy"],
        "cold": ["cool", "chilly", "freezing", "icy"],
        "cool": ["cold", "chilly", "refreshing"],
        "buy": ["purchase", "get", "acquire", "shop"],
        "purchase": ["buy", "get", "acquire"],
        "sell": ["trade", "offer", "vend"],
        "trade": ["sell", "exchange", "barter"],
        "learn": ["study", "educate", "instruct"],
        "study": ["learn", "research", "examine"],
        "teach": ["instruct", "educate", "train"],
        "instruct": ["teach", "educate", "train"],
    },
    "zh": {
        "汽车": ["车辆", "轿车", "车子", "交通工具"],
        "车辆": ["汽车", "轿车", "车子", "交通工具"],
        "轿车": ["汽车", "车辆", "车子", "小车"],
        "小车": ["轿车", "汽车", "车辆"],
        "电脑": ["计算机", "pc", "台式机", "笔记本"],
        "计算机": ["电脑", "pc", "台式机", "笔记本"],
        "笔记本": ["电脑", "笔记本电脑", "laptop"],
        "笔记本电脑": ["笔记本", "电脑", "laptop"],
        "手机": ["电话", "智能手机", "移动电话", "便携电话"],
        "电话": ["手机", "智能手机", "移动电话"],
        "智能手机": ["手机", "电话", "移动电话"],
        "电影": ["影片", "片子", "电影片", "影视"],
        "影片": ["电影", "片子", "电影片"],
        "图片": ["图像", "照片", "相片", "图片"],
        "图像": ["图片", "照片", "相片"],
        "照片": ["图片", "图像", "相片"],
        "相片": ["图片", "图像", "照片"],
        "房子": ["房屋", "住宅", "家", "住房"],
        "房屋": ["房子", "住宅", "家", "住房"],
        "住宅": ["房子", "房屋", "家", "住房"],
        "家": ["房子", "房屋", "住宅", "家庭"],
        "工作": ["职业", "职位", "岗位", "上班"],
        "职业": ["工作", "职位", "岗位", "事业"],
        "职位": ["工作", "职业", "岗位", "职务"],
        "岗位": ["工作", "职业", "职位", "职务"],
        "大": ["巨大", "庞大", "宏大", "硕大", "高大"],
        "巨大": ["大", "庞大", "宏大", "硕大"],
        "小": ["微小", "细小", "迷你", "娇小", "矮小"],
        "微小": ["小", "细小", "迷你", "娇小"],
        "快": ["快速", "迅速", "急速", "飞速", "飞快"],
        "快速": ["快", "迅速", "急速", "飞速"],
        "慢": ["缓慢", "迟缓", "慢慢", "缓缓"],
        "缓慢": ["慢", "迟缓", "慢慢", "缓缓"],
        "好": ["棒", "优秀", "出色", "完美", "很棒"],
        "优秀": ["好", "棒", "出色", "完美"],
        "坏": ["差", "糟糕", "恶劣", "很差", "不好"],
        "差": ["坏", "糟糕", "恶劣", "很差"],
        "开心": ["快乐", "高兴", "愉快", "欢乐", "愉悦"],
        "快乐": ["开心", "高兴", "愉快", "欢乐"],
        "难过": ["伤心", "悲伤", "痛苦", "难受", "忧郁"],
        "伤心": ["难过", "悲伤", "痛苦", "难受"],
        "漂亮": ["美丽", "好看", "靓丽", "俊美", "秀丽"],
        "美丽": ["漂亮", "好看", "靓丽", "俊美"],
        "丑": ["难看", "丑陋", "不好看", "难看"],
        "难看": ["丑", "丑陋", "不好看"],
        "容易": ["简单", "简易", "轻松", "轻易", "不难"],
        "简单": ["容易", "简易", "轻松", "轻易"],
        "困难": ["难", "艰难", "复杂", "棘手", "不易"],
        "难": ["困难", "艰难", "复杂", "棘手"],
        "新": ["新鲜", "崭新", "新颖", "最新", "新潮"],
        "新鲜": ["新", "崭新", "新颖", "最新"],
        "旧": ["老", "古老", "陈旧", "破旧", "老式"],
        "老": ["旧", "古老", "陈旧", "破旧"],
        "热": ["炎热", "酷热", "温暖", "火热"],
        "炎热": ["热", "酷热", "温暖", "火热"],
        "冷": ["寒冷", "冰冷", "凉快", "凉爽"],
        "寒冷": ["冷", "冰冷", "凉快", "凉爽"],
        "买": ["购买", "选购", "购置", "采购"],
        "购买": ["买", "选购", "购置", "采购"],
        "卖": ["出售", "售卖", "销售", "卖出"],
        "出售": ["卖", "售卖", "销售", "卖出"],
        "学习": ["学", "研究", "钻研", "进修", "研习"],
        "学": ["学习", "研究", "钻研", "进修"],
        "教": ["教学", "教导", "教授", "教育", "传授"],
        "教学": ["教", "教导", "教授", "教育"],
    },
    "ja": {
        "車": ["自動車", "乗り物", "ワゴン"],
        "自動車": ["車", "乗り物", "ワゴン"],
        "コンピュータ": ["パソコン", "pc", "ノートパソコン", "デスクトップ"],
        "パソコン": ["コンピュータ", "pc", "ノートパソコン", "デスクトップ"],
        "携帯": ["スマホ", "携帯電話", "スマートフォン"],
        "スマホ": ["携帯", "携帯電話", "スマートフォン"],
        "映画": ["フィルム", "動画", "映像"],
        "フィルム": ["映画", "動画", "映像"],
        "写真": ["画像", "イメージ", "フォト"],
        "画像": ["写真", "イメージ", "フォト"],
        "家": ["住宅", "住まい", "ハウス", "建物"],
        "住宅": ["家", "住まい", "ハウス", "建物"],
        "仕事": ["職業", "勤務", "ジョブ", "業務"],
        "職業": ["仕事", "勤務", "ジョブ", "業務"],
        "大きい": ["巨大", "膨大", "大型", "大きな"],
        "巨大": ["大きい", "膨大", "大型", "大きな"],
        "小さい": ["微小", "細小", "小型", "小さな"],
        "微小": ["小さい", "細小", "小型", "小さな"],
        "速い": ["急速", "迅速", "高速", "早い"],
        "急速": ["速い", "迅速", "高速", "早い"],
        "遅い": ["緩慢", "ゆっくり", "遅れ"],
        "緩慢": ["遅い", "ゆっくり", "遅れ"],
        "良い": ["素晴らしい", "優れた", "すごい", "上手い"],
        "素晴らしい": ["良い", "優れた", "すごい", "上手い"],
        "悪い": ["ひどい", "劣る", "下手", "良くない"],
        "ひどい": ["悪い", "劣る", "下手", "良くない"],
        "楽しい": ["嬉しい", "幸せ", "愉快", "満足"],
        "嬉しい": ["楽しい", "幸せ", "愉快", "満足"],
        "悲しい": ["辛い", "不幸", "切ない", "寂しい"],
        "辛い": ["悲しい", "不幸", "切ない", "寂しい"],
        "美しい": ["綺麗", "素敵", "魅力的", "可愛い"],
        "綺麗": ["美しい", "素敵", "魅力的", "可愛い"],
        "簡単": ["容易", "シンプル", "平易", "やさしい"],
        "容易": ["簡単", "シンプル", "平易", "やさしい"],
        "難しい": ["困難", "複雑", "ややこしい", "手強い"],
        "困難": ["難しい", "複雑", "ややこしい", "手強い"],
        "新しい": ["新鮮", "最新", "斬新", "ニュー"],
        "新鮮": ["新しい", "最新", "斬新", "ニュー"],
        "古い": ["昔", "歴史", "古風", "レトロ"],
        "昔": ["古い", "歴史", "古風", "レトロ"],
        "暑い": ["熱い", "温暖", "ホット", "暑苦しい"],
        "熱い": ["暑い", "温暖", "ホット", "暑苦しい"],
        "寒い": ["冷たい", "涼しい", "クール", "寒冷"],
        "冷たい": ["寒い", "涼しい", "クール", "寒冷"],
    }
}


def get_synonyms_for_language(language: str) -> Dict[str, List[str]]:
    return DEFAULT_SYNONYMS.get(language, {})


def merge_synonyms(base: Dict[str, List[str]], additional: Dict[str, List[str]]) -> Dict[str, List[str]]:
    merged = base.copy()
    for key, value in additional.items():
        if key in merged:
            existing = set(merged[key])
            existing.update(value)
            merged[key] = list(existing)
        else:
            merged[key] = value
    return merged
